services:
  backend:
    build: 
      context: ./backend
    restart: unless-stopped
    networks:
      - internal
  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - internal
    environment:
      - BACKEND_URL=http://backend:8000

networks:
  internal:
    driver: bridge
    